Update run-postman-tests.yml
to add all previous config

diff --git a/.github/workflows/run-postman-tests.yml b/.github/workflows/run-postman-tests.yml
--- a/.github/workflows/run-postman-tests.yml
+++ b/.github/workflows/run-postman-tests.yml
@@ -1,4 +1,4 @@
-name: Main Workflow
+name: Postman tests
 on:
   push:
     branches:
@@ -10,15 +10,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
-
-      # Вызов workflow с именем "Other Workflow"
-      - name: Run previous workflow
-        uses: actions/workflow_run@v2
+        uses: actions/checkout@v3
+      - name: Set up JDK
+        uses: actions/setup-java@v3
         with:
-          workflow: check application runnable
-          token: ${{ secrets.GITHUB_TOKEN }}
-      
+          java-version: 17
+          distribution: 'oracle'
+
+      - name: Start PostgreSQL container
+        run: |
+          docker run --name pg -d -p 5432:5432 \
+            -e POSTGRES_USER=trankwilizator \
+            -e POSTGRES_PASSWORD=517881m \
+            -e POSTGRES_DB=tafl_db \
+            postgres:15-alpine
+
+      - name: Build the application
+        run: mvn clean package
+
+      - name: Stop pg container
+        run: docker stop pg
+
+      - name: Start the application container
+        run: docker-compose up --build
+        
       - name: Install Postman CLI
         run: |
             curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
@@ -33,3 +48,12 @@ jobs:
           postman collection run "${{ github.workspace }}/postman/collections/test registration already exists permanent user.json" -e "19077502-1929ddfd-36b2-46a7-8e81-3ebf52eea139"
           postman collection run "${{ github.workspace }}/postman/collections/testing permanent security.json" -e "19077502-1929ddfd-36b2-46a7-8e81-3ebf52eea139"
           postman collection run "${{ github.workspace }}/postman/collections/testing temp security.json" -e "19077502-1929ddfd-36b2-46a7-8e81-3ebf52eea139"
+
+      - name: Check deployment status
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Deployment successful"
+          else
+            echo "Deployment failed"
+            exit 1
+          fi
